name: build-noble

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read  # wymagane przez checkout@v4
  actions: write  # wymagane przez upload-artifact@v4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cd scripts
          sed -i -E 's/TARGET_UBUNTU_VERSION=(.*)/TARGET_UBUNTU_VERSION="noble"/g' default_config.sh
          ./build.sh -
          cd ..

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-from-scratch
          path: |
            scripts/ubuntu-from-scratch.iso
            scripts/image/md5sum.txt
